### ISSUE TITLE
Practica 11

### ISSUE THREAD

**Issue by Aylin67** [SistemasTecTlaxiaco/actividad-11-practica-de-visualizacion-de-datos-equipo_eaaj#1]
[practica_10[1]TP.pdf](https://github.com/SistemasTecTlaxiaco/actividad-11-practica-de-visualizacion-de-datos-equipo_eaaj/files/15473291/practica_10.1.TP.pdf)

**Comment by josealfredo79** [comment]
Calificacion 19
